[package]
name = "dcs-hemmecs"
version = "0.2.0"
authors = ["Ricardo Maes <ricmzn@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["libloaderapi", "winuser", "errhandlingapi"] }
crossbeam = "0.8"
font-kit = "0.7"
raqote = "0.8"
